### ISSUE TITLE
Class name in @property annotation isn't a link

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#114]
The class/interface name specified in the `@property` annotation:

1. isn't converted to FQCN format
2. isn't a link to it's detail page (when that class is within a project, e.g. not from dependency)

**Comment by Christoph-Harms** [comment]
Hey @aik099, any updates on this? I was about to open an Issue when I saw this one. :) I updated [my minimal test repo](https://github.com/Christoph-Harms/SamiTest) to show this behaviour. Do you have any ideas on how to fix this? I'd be glad to help!

**Comment by aik099** [comment]
Nope. You can send PR if you'd like.

**Comment by Christoph-Harms** [comment]
I'm on it
