### ISSUE TITLE
Version switcher dropdown doesn't work

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#121]
Version switcher dropdown always have 1st version selected regardless of version I'm viewing.
- http://www.qa-tools.io/api/master/index.html - shows `v1.0.0` as selected (wrong, should show `master`)
- http://www.qa-tools.io/api/v1.0.0/index.html - shows `v1.0.0` as selected (correct)

It seems, that some of the recent changes might have caused this because on http://api.symfony.com/2.2/index.html it's working fine.

I'm not sure if that matters, but I'm generating documentation from `master` branch and `v1.0.0` tag. On Symfony all versions are in fact branches.

**Comment by bantu** [comment]
Bump. Was this fixed in the meantime?

**Comment by aik099** [comment]
Nope. I really don't know if we can reuse parsed Twig template cache anymore when dealing with branches/tags, because each of files would have reference to it's branch.

**Comment by bantu** [comment]
@aik099 Caching is nice to have, but here we have broken basic functionality from my point of view.

**Comment by aik099** [comment]
Completely agree. There are other cashing-related issues for example on how DocBlocks are parsed resulting wrong DocBlock shown in generated docs.

**Comment by fabpot** [comment]
The previous version was crafted to make it work with the cache. We should do the same here. Fix the features to make them work with caching, not the other way around. Too bad we did not catch that before.

**Comment by aik099** [comment]
Probably the parts of template, that prevent caching should be somehow parsed separately and injected later in the cached template. I don't really know if it's possible.
