### ISSUE TITLE
Adding a warning for deprecated properties/methods

### ISSUE THREAD

**Issue by tony-co** [FriendsOfPHP/Sami#157]
It would be a useful feature, what does people think?
We are now using Bootstrap so something like a warning label could be nice.

**Comment by aik099** [comment]
Yes. Maybe a badge before property/method, where we show visibility.

**Comment by carbontwelve** [comment]
:+1: to this, I had the same idea just now; it would be quite useful.

**Comment by aik099** [comment]
This has been implemented in #214.
