### ISSUE TITLE
Phar is broken

### ISSUE THREAD

**Issue by mtdowling** [FriendsOfPHP/Sami#160]
I believe that this change has broken Sami: https://github.com/symfony/Yaml/commit/b50000adac00cfc18fcc86b576211a3a01caa550

This change was a breaking change in the Yaml component that disabled the ability to parse from a filename, but rather expects the contents of the Yaml file. Sami is relying on the form that allowed paths to files here: https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Renderer/ThemeSet.php#L40

When running Same right now with a custom theme, you get this error:

```
 [InvalidArgumentException]                                                                                          
  Theme manifest in "/Users/dowling/projects/sdk3/build/artifacts/docs/theme/manifest.yml" must have a "name" entry.
```

This is because the method is being provided an SplFile object that when cast to a string provides the path to the file on disk. Yaml::parse then tries to parse the filename and fails.

Note: this is encountered when using the phar or when using a freshly built phar

**Comment by aik099** [comment]
But do we rely on `master` branch of Yaml component to be affected? If that's a BC break, shouldn't Composer get us correct version without BC break?

**Comment by fabpot** [comment]
I don't understand how this is possible as the code has been removed in the master branch (which is the 3.0 version)

@mtdowling Can you paste the `composer show -i` output to see which deps you have for Sami?

**Comment by mtdowling** [comment]
Ok, so I must have called composer update instead of install. By using the master branch of Sami and building the phar manually, I'm not getting the error I reported. However, the phar linked from the readme has the issue I've reported: http://get.sensiolabs.org/sami.phar. Maybe it needs to be regenerated.

**Comment by mtdowling** [comment]
Nevermind. I take that back. It's actually broken in the master branch. I just git cloned, did a composer install and ran the sami.php script, pointing at my custom theme.

```
php sami.php update ~/projects/sdk3/build/docs.php
```

```
 [InvalidArgumentException]                                                                                          
  Theme manifest in "/Users/dowling/projects/sdk3/build/artifacts/docs/theme/manifest.yml" must have a "name" entry.
```

However, the theme manifest certainly has a name property in the yaml.

```
$ composer.phar show -i
michelf/php-markdown              1.4.1   PHP Markdown
nikic/php-parser                  v1.1.0  A PHP parser written in PHP
phpdocumentor/reflection-docblock 2.0.4   
pimple/pimple                     v3.0.0  Pimple is a simple Dependency Injection Container for PHP 5.3
symfony/console                   v2.6.4  Symfony Console Component
symfony/filesystem                v2.6.4  Symfony Filesystem Component
symfony/finder                    v2.6.4  Symfony Finder Component
symfony/process                   v2.6.4  Symfony Process Component
symfony/yaml                      v2.6.4  Symfony Yaml Component
twig/twig                         v1.18.0 Twig, the flexible, fast, and secure template language for PHP
```

I'll send a PR to address this.

**Comment by mtdowling** [comment]
The latest deployed phar is broken as well:

```
 [ErrorException]                                                                                                                                                     
  Notice: Undefined property: PhpParser\Node\Stmt\Trait_::$type in phar:///Users/dowling/projects/sdk3/build/artifacts/sami.phar/Sami/Parser/NodeVisitor.php line 114
```

Building a phar manually using the master branch *without* doing a composer update works as expected. These dependencies work:

```
$ composer.phar show -i
michelf/php-markdown              1.4.1   PHP Markdown
nikic/php-parser                  v1.1.0  A PHP parser written in PHP
phpdocumentor/reflection-docblock 2.0.4   
pimple/pimple                     v3.0.0  Pimple is a simple Dependency Injection Container for PHP 5.3
symfony/console                   v2.6.4  Symfony Console Component
symfony/filesystem                v2.6.4  Symfony Filesystem Component
symfony/finder                    v2.6.4  Symfony Finder Component
symfony/process                   v2.6.4  Symfony Process Component
symfony/yaml                      v2.6.4  Symfony Yaml Component
twig/twig                         v1.18.0 Twig, the flexible, fast, and secure template language for PHP
```

I'm guessing that one of the dependency bumps (probably phpparser) is causing this error.

**Comment by GrahamCampbell** [comment]
https://github.com/FriendsOfPHP/Sami/issues/159
