### ISSUE TITLE
Document namespace functions

### ISSUE THREAD

**Issue by mtdowling** [FriendsOfPHP/Sami#161]
Adding this issue so that we can track this feature request: document functions in namespaces. Lots of projects are doing this nowadays, so it would be nice if Sami supported it. For example: https://github.com/guzzle/guzzle/blob/v6/src/functions.php

**Comment by aik099** [comment]
When functions in namespaces were introduced in PHP? Can functions be imported individually?

I guess if Parser we're using supports that then adding this feature is no big deal.

**Comment by mtdowling** [comment]
AFAIK, they've been supported since namespaces were added in 5.3.

This is a blocker for us to ship the v3 of the AWS SDK for PHP, so I'll probably take a stab at this soon.

**Comment by aik099** [comment]
Current tree on the left is class/interface/trait based and I don't know where global functions are listed currently or if they are supported at all.

**Comment by mtdowling** [comment]
The namespace specific funcitons I'm referencing would be listed per/namespace so on each namespace page.

**Comment by Rask** [comment]
Some generic file header collection for template/generic files would be awesome too. Our projects have some documentation set into the template file headers as such:

```php
<?php

/**
 * template-name.php
 *
 * This template is used to output a certain template.
 *
 * @since 0.1.0
 * @updated 0.2.0
 * @author Firstname Lastname
 */

...
```

So perhaps the document generator could handle files without any class or function declarations as template or generic files?

**Comment by aik099** [comment]
@Rask , I don't quite understand what you're offering. Your files have File-level DocBlock, but how does it affect documentation generation of file itself doesn't contain any class/interface inside?

**Comment by fabpot** [comment]
Closing as this is indeed not supported. As we had several issues about the same topic, I suppose it would make sense to implement this feature. As I won't implement it myself, I'm closing this ticket. Anybody can of course submit a pull request for this.
