### ISSUE TITLE
Issues with GitVersionCollection.

### ISSUE THREAD

**Issue by NicholasJohn16** [FriendsOfPHP/Sami#170]
I have the following code in my `config.php`:

    	$versions = GitVersionCollection::create($dir)
		->addFromTags('v4.*')
		->add('master', 'master branch');

For some reason, this doesn't work. The biggest issue is with `master`. Whenever I trigger `update` I get the following error:

    [RuntimeException]
    Unable to switch to version "master" as the repository is not clean.

Though, I checked the repository with `git status` and it states the working directory is clean.  Just to be safe, I cloned a fresh copy of the repository from github and I get the same error even though I don't make any modifications.

If I remove `master` and just attempt to run the tags, it runs for about a second and then ends without any error or documentation being generated. The repository has several tags from v4.0.0 to v4.1.2. If I remove the GitVersionCollection and just run with the current files in the directory, it runs correctly.

Any help in debugging this? I'm on Windows 8.1 x64 if that helps. The repository is [anahitasocial/anahita](https://github.com/anahitasocial/anahita).

**Comment by aik099** [comment]
Please provide this:

* content of Sami configuration file 
* command you're using to run Sami
* used Sami version (even better the `composer show -i` command output)
* path to directory you're running Sami command in

**Comment by NicholasJohn16** [comment]
I'm still having this issue.

**config.php**
````
<?php 

	use Sami\Sami;
	use Sami\RemoteRepository\GitHubRemoteRepository;
	use Sami\Version\GitVersionCollection;
	use Symfony\Component\Finder\Finder;
	
	$dir = 'C:/wamp/www/anahita-workspace/fromscratch';
	
	$iterator = Finder::create()
		->files()
		->name('*.php')
		->exclude('Console')
		->exclude('tasks')
		->exclude('vendor/composer')
		->exclude('vendor/dg')
		->exclude('vendor/easybook')
		->exclude('vendor/joomla')
		->exclude('vendor/mc')
		->exclude('vendor/symfony')
		->in($dir);
		
	$repository = new GitHubRemoteRepository('anahitasocial/anahita', $dir);
	
	$versions = GitVersionCollection::create($dir)
		->addFromTags('v4.*')
		->add('master', 'master branch');
	
	$options = array( 
		'title' => 'Anahita Social Network Platform API',
		'build_dir' => 'C:/wamp/www/anahita-workspace/api/build',
		'cache_dir' => 'C:/wamp/www/anahita-workspace/api/cache',
		'remote_repository' => $repository,
		'versions' => $versions,
		'simulate_namespaces' => true
	);
	
return new Sami($iterator, $options);
````
**Command**
    C:\wamp\www\tools\sami>php sami.php update C:/wamp/www/anahita-workspace/api/con
fig.php

**Version**
    Sami version 3.0.4-DEV by Fabien Potencier

**Path**
    C:\wamp\www\tools\sami\

**Comment by aik099** [comment]
With your config I have following Sami output:

```
 Updating project 

Version master
  Parsing   done
  Rendering done

 Version    Updated C    Removed C 
   master         1503            0

 Version    Updated C    Updated N    Removed C    Removed N 
   master         1473          108            0            0
```
Looks like it only generates documentation for `master` branch.

**Comment by aik099** [comment]
There are several issues with your config:

1. both `build_dir` and `cache_dir` should end up with `/%version` to place each documentation in a sub-folder names as tag/branch
2. for 4.x versions tags doesn't start with `v` letter, so `'v4.*'` should become `'4.*'` to get actual tags

**Comment by aik099** [comment]
With updated config output of Sami is what I expected it to be:

```
 Updating project 

Version 4.0.0
  Parsing   done
  Rendering done

Version 4.0.1
  Parsing   done
  Rendering done

Version 4.0.2
  Parsing   done
  Rendering done

Version 4.0.3
  Parsing   done

Version 4.0.4
  Parsing   done

Version 4.1.0
  Parsing   done
  Rendering done

Version 4.1.1
  Parsing   done
  Rendering done

Version 4.1.2
  Parsing   done
  Rendering done

Version master
  Parsing   done
  Rendering done

 Version    Updated C    Removed C 
    4.0.0         1478            0
    4.0.1           70            0
    4.0.2           69            0
    4.0.3           66            0
    4.0.4           66            0
    4.1.0          157            2
    4.1.1          115            3
    4.1.2           95            4
   master          102            2

 Version    Updated C    Updated N    Removed C    Removed N 
    4.0.0         1445          108            0            0
    4.0.1            4            0            0            0
    4.0.2            9            0            0            0
    4.0.3            0            0            0            0
    4.0.4            0            0            0            0
    4.1.0           95            0            2            0
    4.1.1           54            0            3            0
    4.1.2           39            0            4            0
   master           42            0            2            0
```

**Comment by aik099** [comment]
I'm on Mac however. Maybe it's Windows-specific issue. @stof if I recall correctly you're using Windows for development. Could you please try reproducing the described issue.

**Comment by stof** [comment]
@aik099 I switched to Ubuntu in September 2014

**Comment by NicholasJohn16** [comment]
I made the changes to the `config.php`. Yup its a Windows issue from [this line](https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Version/GitVersionCollection.php#L45).  `grep` and `wc` are Unix commands. If I removed those two sections, it runs correctly.

**Comment by aik099** [comment]
Not sure if the result is correct though. If it is working without `grep` and `wc` usage, then why they are there in the first place.

**Comment by stof** [comment]
Well, it runs correctly, but it does not mean it detects the right thing...
