### ISSUE TITLE
Namespace link in tree is "/.html"

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#174]
If namespace contains only other namespaces, then link to it in class tree is "/.html" instead of "/path/to/namespace.html":
![sami_emptynamespacebrokenlink](https://cloud.githubusercontent.com/assets/1277526/8633053/05ab5b16-27c0-11e5-985a-9fe3e021dba0.png)

URL: http://api.qa-tools.io/master/

**Comment by mlessnau** [comment]
I'm observing the same behavior using v3.0.6

**Comment by aik099** [comment]
It's a bug in a new bootstrap theme used in Sami 3.x release, because in old frame based theme these items in tree where not clickable at all.

**Comment by kevinkhill** [comment]
Curious if there is a fix in the works? I would love to try and dig into the source, but I don't have much free time. I would be happy to test if a fix is made.

**Comment by righter** [comment]
If a class file with a namespace exists in the directory, this bug is not encountered. If a directory only contains other directories, you'll run into this bug.

One way to approach a fix for this is this: if a directory only contains directories, then derive a namespace for current directory based on a child directory. 

That might not be the best way to fix it but I can't think of anything else at the moment...

**Comment by jclebreton** [comment]
I have the same bug using version 3.2.1-DEV

**Comment by aik099** [comment]
Only an issue for code, that uses PSR-0. Probably majority of Sami users switched to PSR-4 and therefore they don't have this problem anymore.

**Comment by jclebreton** [comment]
@aik099 thx for your reply, however i'm using PSR4 autoload

**Comment by aik099** [comment]
I'm referring to autoloading, because in PSR-0 world you most likely will have directories without PHP files in them just to satisfy PSR-0. Not that it's directly related to the mentioned issue.

**Comment by jclebreton** [comment]
@aik099 ok thanks

**Comment by vluzrmos** [comment]
Same issue, I'm using PSR-4

**Comment by TiS** [comment]
If you, say, use recommended namespace structure "vendor/project", then vendor namespace likely won't have any files (at least - any code files). So PSR-4 is not sufficient.

Anyway, the namespace doc files are generated. Only problem is in tree linking to them.

**Comment by aik099** [comment]
Anyway anybody participating in this discussion is welcome to send PR with a fix.

**Comment by TiS** [comment]
I've found this line of code inside `Sami\Tree.php[58]`:

```php
$url = $parts[count($parts) - 1] && count($cl) ? $namespace : '';
```

It's easy to replace it with just `$url = $namespace;` , but I'm not sure, why it looks like that in the first place. Any of the developers, can you enlighten me?

**Comment by aik099** [comment]
I have no idea, but maybe commit history of that file would tell.

**Comment by TiS** [comment]
Currently I'm experimenting with setting this line to 

```php
$url = $parts[count($parts) - 1] ? $namespace : '';
```

But you're right, I'll check with commit history.

**Comment by TiS** [comment]
Ok, Fabien directly changed this line in #e0d7d92 . Further checks are needed then :)

**Comment by TiS** [comment]
I've added a PR. Links should be generated for all namespaces containing classes **or** sub namespaces.

**Comment by TiS** [comment]
Any comments about my PR so far???

**Comment by aik099** [comment]
The @fabpot seems to be busy, because only he can merge PRs.

**Comment by net-tools** [comment]
Looking for help about this issue (empty namespaces producing a broken link), I see that the PR is still waiting from Apr 27... Up ?

**Comment by DIOHz0r** [comment]
Hello, 

I'm having this issue on our project https://github.com/glpi-project/php-library-glpi

Sami script creates that '.html' file on the root directory and the namespaces pages aren't generated giving an error 404

What could be happening?
