### ISSUE TITLE
Protected methods should be documented by default

### ISSUE THREAD

**Issue by stof** [FriendsOfPHP/Sami#175]
Protected methods are extension point in your code. So a better default would be to document them and hide only private methods (which indeed don't make sense in the API doc).
They should of course be visually different from public methods.

Note that this impacts the Symfony documentation. The doc links to the API doc for some protected methods (for instance the controller shortcut methods) and recently discovered they were dead links.

**Comment by aik099** [comment]
> Protected methods are extension point in your code. So a better default would be to document them and hide only private methods (which indeed don't make sense in the API doc).

It's just a matter of changing default filter used if none was supplied in user config file.

> They should of course be visually different from public methods.

It's already done by showing method scope (`protected` word or some icon) before method/property names.

**Comment by fabpot** [comment]
see #236
