### ISSUE TITLE
Methods with default scope are not appearing in documentation

### ISSUE THREAD

**Issue by exse2** [FriendsOfPHP/Sami#178]
If you declare Method with "function methodName()" instead of "public function methodName()",
the method is not shown in generated documentation. It should be, because omitting scope means "public" by default.

**Comment by aik099** [comment]
Relevant code line: https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Parser/NodeVisitor.php#L143

This might as well be a bug in used `nikic/php-parser` library because it's data is being used to detect method scope.

**Comment by exse2** [comment]
Thank you for the pointer. 
Hacked it for my purposes:
In Sami/Reflection/MethodReflection.php, replace the "isPublic" method with:
    public function isPublic() 
    {
        if($this->modifiers === '0') {
                //"public function" without scope = default true
                return(true);
        }
        if($this->modifiers === '8') {
                //"static function" without scope = default true
                return(true);
        }
        return self::MODIFIER_PUBLIC === (self::MODIFIER_PUBLIC & $this->modifiers);
    }

**Comment by aik099** [comment]
Please use fenced code blocks to enable syntax highlight.

Also instead you might check if none of public/protected/private modifiers is found, then consider method as public.

**Comment by fabpot** [comment]
fixed in 8ee8d770d3b0c4f865cc78acf1aa6c0a013fdd94

**Comment by aik099** [comment]
@fabpot , I've added some comments to https://github.com/FriendsOfPHP/Sami/commit/8ee8d770d3b0c4f865cc78acf1aa6c0a013fdd94 .
