### ISSUE TITLE
Documentation Pages

### ISSUE THREAD

**Issue by mattfarina** [FriendsOfPHP/Sami#18]
One of my favorite features in Doxgen is the ability to produce documentation pages. This could be a landing page for the API docs site. It could be a tutorial or other reference. This is a useful feature.

Would something like this be in the roadmap?

**Comment by chrismichaels84** [comment]
I have forked this repo and have begun working on a mkdocs-like documentation for Sami. Give me a week or two before I push a release :)

Please, please open an issue on my fork for a wishlist.

http://github.com/chrismichaels84/Sami

**Comment by aik099** [comment]
You mean https://readthedocs.org/ one? If so, then create it in RST format please because it has more features then files in markdown.

**Comment by chrismichaels84** [comment]
If I can find a good RST parser for composer/php, I'd be happy to give users the choice. I'm using Github flavored markdown.

**Comment by ima-tech** [comment]
That would be really something I'd be looking for.

**Comment by aik099** [comment]
@chrismichaels84 so you want to create a documentation for Sami project besides one on https://github.com/FriendsOfPHP/Sami/blob/master/README.rst?

Why you need the RST parser?

**Comment by chrismichaels84** [comment]
@aik099 I'm sorry I misunderstood your comment. I am not creating new documentation. I am creating the ability to add documentation (like guides) pages to your Sami auto-generated API. You write documentation in markdown and Sami wrangles them together, outputs html (using your twig theme) and adds a "Guides" tab to the top so users can read your "getting started", "advanced usage", "contributing" stuff.

Write now, you can only write that documentation in markdown because I have not found a good RST parser in php and don't have the time to build one.

**Comment by aik099** [comment]
I won't be mixing project usage documentation with api documentation, that is done by Sami.

**Comment by chrismichaels84** [comment]
Sami already does that? How?

**Comment by aik099** [comment]
Are you sure? Any example of a project, that is using this and it's Sami config file?

**Comment by chrismichaels84** [comment]
I am confused, lol. To my knowledge, Sami only scans source files and creates beautiful documentation based on docblocs and reflection. There is no ability to add pages of documentation about overall usage like you can with mkdocs.

If it is possible to use Sami to create usage documentation (guides), please let me know. I haven't found it.

**Comment by aik099** [comment]
> Sami already does that? How?

I thought you meant, that Sami already can include static pages in generated docs. I bet it don't have such feature. And obviously you want to add it, but I think that Sami generated docs isn't the place for static pages at all.

**Comment by chrismichaels84** [comment]
Fair enough. I'd just like all my documentation to be in one place instead of sending people to two different docs sources. Personal preference :)

**Comment by aik099** [comment]
Unfortunately for a FOSS project we don't have much of choice, but to use free hosting from different service providers: documentation on one domain, api documentation on other domain, website on other domain.

**Comment by serieznyi** [comment]
@mattfarina I aggree with @aik099 what generating documentation is too much for Sami

**Comment by fabpot** [comment]
Closing this issue as this is out of the scope of this project.
