### ISSUE TITLE
Line break after first period character

### ISSUE THREAD

**Issue by xelan** [FriendsOfPHP/Sami#183]
Sami seems to insert a line break to the summary of a method after the first occuring period character. For example, I have a method with the description

`Adds a simple (no multipart, no attachments, ...) message.`

__Expected documentation output:__
```
Adds a simple (no multipart, no attachments, ...) message.
```
__Actual documentation output:__
```
Adds a simple (no multipart, no attachments, .
..) message.
```
__Tested version__
```shell
$ sami --version
Sami version 3.1.0-DEV by Fabien Potencier
```
Thank you very much!

**Comment by aik099** [comment]
This is bug. I thought that we're using PhpDocumentator DocBlock parser to determine method short and long description.

**Comment by fabpot** [comment]
We are using `phpdocumentor/reflection-docblock`

**Comment by aik099** [comment]
@xelan , if you can reproduce the problem even without Sami, then report bug to https://github.com/phpDocumentor/ReflectionDocBlock instead.

**Comment by xelan** [comment]
Reported as phpDocumentor/ReflectionDocBlock#63
