### ISSUE TITLE
Documentation about tag managed by Sami

### ISSUE THREAD

**Issue by Ducatel** [FriendsOfPHP/Sami#201]
Hi everybody,

I trying to find the list of tag managed by Sami.
Can you tell me where this list is ?

Another question, is it possible to add in Sami the @author and [@example](https://phpdoc.org/docs/latest/references/phpdoc/tags/example.html) tags ?

Thanks in advance for your help ;)

**Comment by aik099** [comment]
Can you explain the problem you're experiencing instead? Like the `@author` tag from DocBlock of method method isn't shown in generated documentation, but `@param` and `@return` tags are.

**Comment by Ducatel** [comment]
ok.

I need to link/display some sample of code on class. This is useful for explain how use the class.

I also need to indicate quickly who write a class/method. This can be done by `@author` tag.

And I want to known the list of tags managed by Sami for making better my doc workflow. 

I don't know if I'm clear ?

**Comment by aik099** [comment]
Have you tried to do it and it didn't work? I don't know the exact list of supported tags (maybe they are listed in documentation). It's easier to try and see what doesn't work.

**Comment by Ducatel** [comment]
Yes I have tried and it does nothing.
You found a documentation ?? I just saw a readme, can you send me the link to the documentation ?

**Comment by aik099** [comment]
That's the only documentation available unfortunately, except actual code.

I've checked in code and found this:

* all tags found in DocBlocks are preserved
* only some are actually used in the `class.twig` template

This way if you need to display additional tags, then you need to override `class.twig` template and output what you need.

For example `@see` tag is handled is displayed like this:

```twig
{% if method.tags('see') %}
    <h4>See also</h4>

    {{ block('see') }}
{% endif %}
```

I guess there is `see` block defined somewhere else, which uses it.

**Comment by Ducatel** [comment]
OK, I will try on this way ;)
Thanks for your help
