### ISSUE TITLE
sami not support the @see/@deprecated .... tags?

### ISSUE THREAD

**Issue by mumutou** [FriendsOfPHP/Sami#203]
sami not support the @see/@deprecated .... tags?

**Comment by aik099** [comment]
The `@see` tags is supported for sure (see #201). Not sure about `@deprecated` tag though. Anyway tags are collected, but maybe not displayed by default in currently used Twig templates.

**Comment by mumutou** [comment]
oh,yes, sami support @see, but @deprecated is excluded

**Comment by aik099** [comment]
You can send PR with support for `@deprecated` tag.

**Comment by mumutou** [comment]
sorry, I don't know how to send PR. can you give a advise?

**Comment by aik099** [comment]
Luckily GitHub has it all docummented: https://help.github.com/articles/using-pull-requests/.

**Comment by schnittstabil** [comment]
@mumutou You have to:
1. [Fork](https://help.github.com/articles/fork-a-repo/) the sami repository (button above)
2. `git clone` your fork to a local directory
3. Run `composer install` etc.
4. change the sources, ideally add some tests for your changes
5. run the tests (`vendor/bin/phpunit`)
6. if everything is fine `git commit` your changes
7. `git push` your commits to your fork
8. visit your fork (https://github.com/mumutou/Sami) and [create the pull request](https://help.github.com/articles/creating-a-pull-request/)

**Comment by mumutou** [comment]
ok, i see
