### ISSUE TITLE
Fatal Error when using SymfonyFilter and parsing non-"@api" Classes

### ISSUE THREAD

**Issue by Christoph-Harms** [FriendsOfPHP/Sami#204]
Given only some of the Classes of the codebase should be present in the public api-documentation, one can use the `SymfonyFilter` (or write a Filter that filters classes having the `@api`-Tag). However, doing so results in

```console
PHP Fatal error:  Call to a member function addTrait() on null in path/to/vendor/sami/sami/Sami/Parser/NodeVisitor.php on line 229
```

when there are classes without the `@api`-Tag (if all classes have the tag, no error occurs). The corresponding part of `NodeVisitor.php` is

```php
protected function addTraitUse(TraitUseNode $node)
    {
        foreach ($node->traits as $trait) {
            $this->context->getClass()->addTrait((string) $trait); // This line produces the error
        }
    }
``` 

So it looks like `getClass()` returns `null` for classes not having the `@api`-Tag (because of the filter), then trying to call a method on that obviously results in a fatal.

**Comment by aik099** [comment]
And traits are used by that class, right?

**Comment by Christoph-Harms** [comment]
Yep.

**Comment by Christoph-Harms** [comment]
As a hotfix, adding

```php
if ($this->context->getClass() === null)
{
    return;
}
```

to the beginning of the method seems to work. I haven't tested this thoroughly yet, though.

**Comment by aik099** [comment]
Does the error show up, when you're using other filtering class, like `TrueFilter`?

**Comment by Christoph-Harms** [comment]
No, as `TrueFilter` always returns `true` (duh :D), the error doesn't show up.

**Comment by Christoph-Harms** [comment]
Thanks for the extremely quick reaction time, btw!

**Comment by aik099** [comment]
So the bug must be in the filter itself I guess.

In either case it would be great if you can provide:

1. a project repo where problem can be reproduced
2. a Sami config file used
3. command line you're using to invoke Sami

**Comment by Christoph-Harms** [comment]
OK, I'll do so ASAP.

**Comment by Christoph-Harms** [comment]
I've quickly put together a repo with the minimum code necessary to reproduce the error I can come up with: https://github.com/Christoph-Harms/SamiTest

Simply clone, run `composer install` and then, from the repo's base directory, 

`php vendor/sami/sami/sami.php update samidoc/config.php`

to produce the error. Note that the error does not occur if you add the `@api`-Tag to the `ClassA`-class.

Cheers
Christoph

**Comment by Christoph-Harms** [comment]
> So the bug must be in the filter itself I guess.

I don't think that's the case. The filter just returns `true` or `false` for classes, methods and properties, based on criteria you can define yourself. There's not much that can go wrong there.

The problem is (to my mind), that *if* a filter returns `false` for a class and that class uses a trait, Sami tries to document that trait on a class it doesn't know, resulting in said error.

**Comment by aik099** [comment]
It's easier to debug both cases (when filter returns true or false) and see what happens for class that uses trait and doesn't use it. 4 test cases in total.

**Comment by aik099** [comment]
@Christoph-Harms I'm not getting any Fatal Error with repo you've provided. Maybe you've fixed that to show problem in #205?

**Comment by Christoph-Harms** [comment]
That's true. To get the error, just remove the `@api`-Tag from one or both of the classes.

**Comment by aik099** [comment]
@Christoph-Harms , the #208 should fix it.

**Comment by Christoph-Harms** [comment]
Oh balls, now I've created a second PR because I didn't see your comment there... Just reject that, then. :) 

LOL, we even made the exact same change. :)
