### ISSUE TITLE
property.shortdesc malformed?

### ISSUE THREAD

**Issue by Christoph-Harms** [FriendsOfPHP/Sami#205]
This is from a "class"-Page of my Documentation:

![bildschirmfoto 2016-05-11 um 15 14 52](https://cloud.githubusercontent.com/assets/17005834/15182175/80b93560-178b-11e6-9751-7b80295c9d35.png)

Notice that the property's type and name get repeated in front of the description without any whitespace. The corresponding DocBlock looks like this:

```php
/**
[...]
 * @property int $id The ID of the Category object.
 * @property int $parentCategoryId The ID of the parent category, if applicable
[...]
 */
```

Did I do something wrong in the DocBlock? Or is this indeed a bug?

Cheers
Christoph

**Comment by aik099** [comment]
The DocBlock looks good.

This can be bug in following places, but without checking in the code I can't tell:

* library we're using to parse DocBlocks
* Twig template where data is being displayed

**Comment by Christoph-Harms** [comment]
I've updated the Repo I created for #204 so now when you run

`php vendor/sami/sami/sami.php update samidoc/config.php``,

the generated documentation includes this.

**Comment by Christoph-Harms** [comment]
As a hotfix, modifying `class.twig` in the following way:

```twig
{% block properties %}
    <table class="table table-condensed">
        {% for property in properties %}
            <tr>
                <td class="type" id="property_{{ property.name|raw }}">
                    {% if property.static %}static{% endif %}
                    {% if property.protected %}protected{% endif %}
                    {% if property.private %}private{% endif %}
                    {{ hint_link(property.hint) }}
                </td>
                <td>${{ property.name|raw }}</td>
                /****************************************************************
                 The following line contains the hotfix
                ****************************************************************/
                <td class="last">{{ property.shortdesc|desc(class)|slice(hint_link(property.hint)|length + property.name|raw|length) }} </td>
                <td>
                    {%- if property.class is not same as(class) -%}
                        <small>from&nbsp;{{ property_link(property, false, true) }}</small>
                    {%- endif -%}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
```

seems to work.

**Comment by aik099** [comment]
Can you please show what's changed (diff) of that line?

**Comment by aik099** [comment]
Or even send a PR?

**Comment by Christoph-Harms** [comment]
I could, though this is really a dirty fix. Somehow, `property.shortdesc|desc(class)` returns a string including type and name in front of the description. To get rid of it, I simply `slice`'d it (as in: took a substring of it with the beginning cut off).

Original line:
```twig
<td class="last">{{ property.shortdesc|desc(class) }}</td>
```

My line with the dirty fix:
```twig
<td class="last">{{ property.shortdesc|desc(class)|slice(hint_link(property.hint)|length + property.name|raw|length) }} </td>
```

If you'd like, I'll send a PR regardless, of course. :)

**Comment by aik099** [comment]
Maybe underlying DocBlock parsing library has an error. Can you please debug it?

**Comment by Christoph-Harms** [comment]
Sure, I'll be glad to! :) It's going to take some time 'though, I'm running a little low on spare time at the moment. But I should be able to get to it before the end of next week.

**Comment by aik099** [comment]
Same problem here. At least I try to respond on GitHub to at least organize people into doing things.

**Comment by Christoph-Harms** [comment]
I appreciate that! It's not to be taken for granted that the response time on issues for an open source project is that short. Keep up the good work!

**Comment by aik099** [comment]
According to PHPDoc website (see https://www.phpdoc.org/docs/latest/references/phpdoc/tags/property.html) the syntax for `@property` tag is as follows:

```
@property [Type] [name] [<description>]
```

In the example repo you've used following code however:

```
@property $someProp Some random property, only introduced to demonstrate a bug
```

In there type is missing. I'm looking into how `@property` is being handled right now, but this is definetly code in Sami side.

**Comment by aik099** [comment]
@Christoph-Harms , I've created #206 PR, that fixes this issue.
