### ISSUE TITLE
Class 'PhpParser\NodeVisitorAbstract' not found

### ISSUE THREAD

**Issue by zairy** [FriendsOfPHP/Sami#210]
anyone can help me how to resolve this. iam new to this. thank you

FatalErrorException in ClosureLocatorVisitor.php line 18:
Class 'PhpParser\NodeVisitorAbstract' not found

![image](https://cloud.githubusercontent.com/assets/19425951/15352730/33e691dc-1d18-11e6-9664-4921e5d93413.png)

**Comment by aik099** [comment]
At which stage of Sami workflow you're encountering this error:

1. documentation generation
2. when viewing a particular page (e.g. list of namespaces, class page) in generated documentation

The screenshot is from some fancy exception handler and Sami doesn't have any.

**Comment by aik099** [comment]
And Sami doesn't have "ClosureLocatorVisitor.php" file. So what are you're using must be some kind of Sami fork with more features.

**Comment by fabpot** [comment]
Closing as there is no feedback from the reporter. Feel free to reopen if you have more information to share.
