### ISSUE TITLE
Syntax error, unexpected T_LIST, expecting T_STRING when function with name "list"

### ISSUE THREAD

**Issue by sas1024** [FriendsOfPHP/Sami#216]
PHP 7.0.6, lastest Sami (3.3.0-dev)

When I add function like this:
`    public function list(int $timestampFrom, int $timestampTo)`

then I got error `Syntax error, unexpected T_LIST, expecting T_STRING`

while rendering documentation.

**Comment by aik099** [comment]
Interesting. Probably a PHP-Parser library related error, that we're using.

**Comment by GrahamCampbell** [comment]
It's because `list` is a semi-reserved word.

**Comment by aik099** [comment]
@GrahamCampbell , in PHP 7 you can use reserved keywords as function/method names. That's why code example from task is absolutely valid in there.

**Comment by GrahamCampbell** [comment]
@aik099 Yeh, I know. I'm telling you why it's not working.

**Comment by GrahamCampbell** [comment]
**semi-reserved**

**Comment by aik099** [comment]
Same as what I was saying. Syntax change in PHP that isn't yet supported by PHP-Parser probably.

**Comment by sas1024** [comment]
PHP-Parser 2.x must helps, I think.
