### ISSUE TITLE
[Question] Nikic/PHP-parser version

### ISSUE THREAD

**Issue by KKSzymanowski** [FriendsOfPHP/Sami#217]
Hi.

Why do you require `nikic/php-parser` 1.\*, not 2.\*? 
Is it because of required PHP version?
Do you have a plan for a branch that uses 2.*?

Thanks.

**Comment by aik099** [comment]
No restrictions really. We can:

1. use `"nikic/php-parser": "^1.2|^2.0"` as dependency in `composer.json`
2. update the code to detect which PHP-Parser version used, like done in https://github.com/goaop/parser-reflection/blob/master/src/ReflectionEngine.php#L58-L69

**Comment by KKSzymanowski** [comment]
In that case I will send a PR soon. I asked because I ran into several dependency collisions when using your package and because of that had to downgrade to php-parser 1.*.

Just one thing: `php-parser 2.*` requires PHP `>=5.4` whereas your package requires PHP `>=5.3.9`. Are you willing to raise the requirement for minimum PHP version or do you wish to create a new branch for backward compatibility.

**Comment by aik099** [comment]
> Are you willing to raise the requirement for minimum PHP version or do you wish to create a new branch for backward compatibility.

No need, because we'll be supporting both PHP-Parser major versions at same time so for people on PHP 5.3 Composer will get PHP-Parser 1.x as it does currently for all.

**Comment by KKSzymanowski** [comment]
You're right. I haven't thought about this.
