### ISSUE TITLE
Reflection error when generating the docs

### ISSUE THREAD

**Issue by phcorp** [FriendsOfPHP/Sami#218]
I encounter the following issue when trying to generate the docs for my project:
```
ERROR: Catchable Fatal Error: Argument 2 passed to phpDocumentor\Reflection\DocBlock::__construct() must be an instance of phpDocumentor\Reflection\DocBlock\Description, instance of phpDocumentor\Reflection\DocBlock\Context given, called in phar:///[path]/sami.phar/Sami/Parser/DocBlockParser.php on line 27 and defined in /[path]/[project]/vendor/phpdocumentor/reflection-docblock/src/DocBlock.php line 52 on "[namespace]/[class]::[method]" in /[path]/[project]/[filename]:[line]
```

This error didn't occur before, I can't explain it.

**Comment by phcorp** [comment]
It seems that including the composer autoloader of my project in sami bootstrap file was quite confusing. So it's repaired, I close the issue.

**Comment by aik099** [comment]
> It seems that including the composer autoloader of my project in sami bootstrap file was quite confusing.

What do you mean? Sami have no need to include autoloader of a project to generate it's docs.

**Comment by aik099** [comment]
Google that error suggests, that this might be dependency version conflict where somehow classes of newer phpDocumentator version were used in Sami. I'm not able to reproduce issue locally.
