### ISSUE TITLE
Classes not in "master" branch now shown in tree

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#219]
In a project I have `develop` (primary) and `master` branches. I generate documentation for both at the same time and class, that is added only in `develop` branch is never shown in left navigation tree:

![2016-06-25_2001](https://cloud.githubusercontent.com/assets/1277526/16358027/dbea1268-3b0f-11e6-8cab-ac740b555fe6.png)

The interesting part is that if I search for that class using search box on the left, then class is found.

---

I bet this is caching related issues where left navigation tree is generated once and then reused for each branch.

**Comment by aik099** [comment]
When I generate docs for 1 branch only (the `develop`) then tree content is correct.

**Comment by aaemnnosttv** [comment]
I have the same problem.  Looks like it's the same thing as described in #62 .

No problem when using `--only-version=` with branch or tag, but then you lose the version switcher also.

**Comment by fabpot** [comment]
fixed now
