### ISSUE TITLE
PHPUnit warnings b/c of use of deprecated method un unit tests.

### ISSUE THREAD

**Issue by Christoph-Harms** [FriendsOfPHP/Sami#225]
The deprecated method `PHPUnit_Framework_TestCase::getMock()` is used in various tests which leads to warnings when running PHPUnit (see screenshot).

<img width="1411" alt="bildschirmfoto 2016-07-07 um 11 55 19" src="https://cloud.githubusercontent.com/assets/17005834/16653263/1588e6c2-4450-11e6-8928-eb30fb6450f6.png">

**Comment by fabpot** [comment]
Fixed now.
