### ISSUE TITLE
Parsing error when invoking a closure

### ISSUE THREAD

**Issue by krzysiekpiasecki** [FriendsOfPHP/Sami#228]
There is a parsing error when invoking a closure.

## The class source code

```php
declare (strict_types = 1);

final class DualP implements PredicateInterface
{
    private $predicate;

    public function __construct(PredicateInterface $predicate)
    {
        $this->predicate = $predicate;
    }

    public function __invoke(...$subject): bool
    {
        if (2 !== count($subject)) {
            throw new \BadMethodCallException(
                'This is the predicate of two subjects'
            );
        }

        return ($this->predicate)(...$subject);
    }
}
```

## Debug info

__Error line__

```php
return ($this->predicate)(...$subject);
```

__Error message__
> ERROR: Syntax error, unexpected '(' on line 41 on "./src/Predicate/DualP.php" in ./src/Predicate/DualP.php:0

Using ```call_user_func_array``` instead of direct invocation works good. Is it a dependency error?

**Comment by aik099** [comment]
Related issue: #216

This all leads to need of upgrading PHP-Parser depedency.
