### ISSUE TITLE
Sami is not compatible with Laravel 5.3

### ISSUE THREAD

**Issue by davidsoderberg** [FriendsOfPHP/Sami#232]
I am using Larvel 5.3 and try to installing Sami 3.3 and gets a few composer error about dependency collisions. How can I solve it?

**Comment by mzur** [comment]
Related to this [comment](https://github.com/FriendsOfPHP/Sami/pull/231#issuecomment-240449214). Laravel 5.3 requires symfony/finder and symfony/console version 3.1.* but Sami requires them in version ~2.1 which are incompatible. I'll try and see if the dependencies can be upgraded for Sami.

**Comment by mzur** [comment]
Just found #192 which should fix this issue.

**Comment by fabpot** [comment]
See #235
