### ISSUE TITLE
[Question] Documenting multiple packages

### ISSUE THREAD

**Issue by hskrasek** [FriendsOfPHP/Sami#240]
I hope this isn't the wrong place to ask such a question, apologies if it is. 

I'm looking to use Sami to document a bunch of internal packages at work, and I was wondering if Sami can handle documenting and navigating between all of those packages?

General example, but if we have a security and a support package can Sami document both and be able to navigate between the two packages? Or would I need to build out each packages docs, and build something to tie them all together?

**Comment by aik099** [comment]
If can configure Sami to inspect different branches/tags in same repository and the switch between them as different version of same project. However if you have different repositories that you want to connect together I'm afraid that it's impossible.

**Comment by hskrasek** [comment]
Yea this is for different repositories. Basically want to do the same thing Laravel does for all of its individual Illuminate packages, without having to have a giant repo containing every single one of our internal packages.

**Comment by fabpot** [comment]
You can generate API docs for several packages, but then, you won't be able to use the Git integration and generate different versions automatically.
