### ISSUE TITLE
[Question] symfony integration

### ISSUE THREAD

**Issue by decima** [FriendsOfPHP/Sami#247]
Hey,
is there any symfony integration, or plan to do so like nelmio's bundle to generate dynamic api doc ?

Do you have any good advice for integrate it in symfony ?

Sorry if it's not the best place for this kind of questions :(

**Comment by brcontainer** [comment]
Both can be installed via composer, so we believe that it is possible to integrate, using composer-autoload and for start use https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Sami.php

**Comment by fabpot** [comment]
No plan to do that. Generating the docs takes time, so it should be done via the CLI from time to time. Anyway, you can probably implement something if you need to.
