### ISSUE TITLE
All class method declarations have "line line" in all generated documentation

### ISSUE THREAD

**Issue by intacctcoleenho** [FriendsOfPHP/Sami#249]
For example, check out http://api.symfony.com/master/Symfony/Bridge/Doctrine/Validator/DoctrineInitializer.html.

![image](https://cloud.githubusercontent.com/assets/17015714/21202653/17ae8218-c204-11e6-8a03-36046a48a2ea.png)

Right side of method declaration has "at line line 26".  Shouldn't this just be "at line 26"?

**Comment by aik099** [comment]
Which version of Sami are you using? I remember fixing it in #221, but not sure if change was released or not.

**Comment by intacctcoleenho** [comment]
version 3.3.* per composer

**Comment by aik099** [comment]
Does it work correctly in `master` branch?

**Comment by net-tools** [comment]
Hi, 

To answer your question, and since @intacttcoleenho has not answered yet, I'm using Sami 3.3.0 through master branch, and I'm also having this issue (if useful, my server is with PHP7).

Hope this could be fixed soon

**Comment by intacctcoleenho** [comment]
@net-tools Thank you for commenting back on using Sami 3.3.0 on master branch.  
@aik099 do you still need me test using master?

**Comment by aik099** [comment]
@intacctcoleenho , nope. Just waiting for somebody to send a PR with a fix.

**Comment by net-tools** [comment]
Hi,

I was going to have a look at the Sami repository to send a PR with the fix, and I noticed that in the current dev-master the issue has been fixed, with #221 and committed.

However, the last stable release being v3.3.0 (from June 7, 2016), and the #221 issue patched on June 21, the current Sami release available on Packagist does not include the fix.

@intacctcoleenho : you may either wait for the next stable release to get live and available through Packagist/Composer, or you could require a @dev version with Composer. However, it seems that recent changes to the PHP parser brought some nasty bugs (issues with namespaces, I noticed), still waiting for a fix...

@aik099, By the way, there's a pending PR from April still waiting to be accepted (issue #174). I understand guys may be busy on other assignments, but that's a pity we send PR that get accepted months later...

**Comment by aik099** [comment]
> but that's a pity we send PR that get accepted months later...

Don't tell me about that. I have sent PRs (not to this repo) that even haven't been reviewed for years. Having a community around FOSS project, where people are always there to review incoming PRs is a problem these days.

**Comment by aik099** [comment]
This doesn't mean, that sent PRs are not considered important. It's just that people are very busy with other things (like work 😄 ) to review them.

**Comment by fabpot** [comment]
Closing as it has been fixed, 4.0 will include the fix and will be released soon.
