### ISSUE TITLE
Broken dev-master

### ISSUE THREAD

**Issue by krzysiekpiasecki** [FriendsOfPHP/Sami#250]
> Block "search_index" on template "layout/base.twig" does not exist.

```
sami/sami  dev-master 2048fcb Sami, an API documentation generator
```

Please test dev-master before pushing ;)

**Comment by aik099** [comment]
Unfortunately documentation generation isn't part of the build, that is executed on Travis CI. Probably it should be.

**Comment by aik099** [comment]
That is result of upgrade from Twig 1.x to Twig 2.x.

After creating test that calls `Project::update` method I've got this on Twig 1.x

```
Silent display of undefined block "search_index" in template "layout/base.twig" is deprecated since version 1.29 and will throw an exception in 2.0. Use the "block('search_index') is defined" expression to test for block existence: 1x
```

and this on Twig 2.x

```
Twig_Error_Runtime: Block "search_index" on template "layout/base.twig" does not exist.
```

**Comment by aik099** [comment]
@krzysiekpiasecki , how have you solved this?

**Comment by fabpot** [comment]
It's not related to not testing before pushing but rather that upstream code changed.

**Comment by fabpot** [comment]
I've just removed this piece of code as it never worked.
