### ISSUE TITLE
Sami dependencies can't be installed

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#254]
When on PHP 5.5 I try (the `master` branch) to do `composer update` inside Sami folder I'm getting:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - remove twig/twig 2.0.x-dev|keep twig/twig dev-master
    - twig/twig 2.x-dev requires php ^7.0 -> your PHP version (5.5.18) does not satisfy that requirement.
    - twig/twig dev-master requires php ^7.0 -> your PHP version (5.5.18) does not satisfy that requirement.
    - Installation request for twig/twig ~2.0@dev -> satisfiable by twig/twig[2.x-dev, 2.0.x-dev].
```

There is something wrong, because PHP requirement for Sami itself is `>=5.5.9`, but Twig wants `^7.0`.

Problem was introduced in #235, where Twig 1.x support was removed.

**Comment by fabpot** [comment]
Indeed, we've just bumped the minimal version fo Twig to PHP 7.

**Comment by aik099** [comment]
Any ideas how to make Sami 5.5 compatible? Maybe reverting #235 and force users, that are getting  Symfony 3 issues use phar version.

**Comment by fabpot** [comment]
I've just updated Composer to drop support for PHP 5.5.

**Comment by aik099** [comment]
Such solution wasn't expected, because Sami always was famous for PHP version tolerance and not useless updating minimal PHP version to support mass movement for PHP 7 without any actual reason.

**Comment by fabpot** [comment]
This change is part of a new major version that is not released yet.
