### ISSUE TITLE
Question: Does sami support PHP 7 return type declare?

### ISSUE THREAD

**Issue by netroby** [FriendsOfPHP/Sami#256]
https://wiki.php.net/rfc/return_types

Question: Does sami support PHP 7 return type declare?

**Comment by fabpot** [comment]
No, this could be added though. Would you like to submit a PR?

**Comment by netroby** [comment]
I need your guide. if we need support it . which files should be changed ?

**Comment by markdunphy** [comment]
Hi - I've implemented this feature in the below pull request. Please have a look when you've got some time :) @fabpot 

https://github.com/FriendsOfPHP/Sami/pull/345
