### ISSUE TITLE
@param with default "0" value is not displayed

### ISSUE THREAD

**Issue by brcontainer** [FriendsOfPHP/Sami#258]
An simple example:

```php
<?php
namespace Foo\Bar;

class Baz
{
    /**
     * Description foo foo bar baz
     *
     * @param int $foobarbaz
     * @return void
     */
    protected function foobar($foobarbaz = 0) {
    }
}
```

After generate:

![1](https://cloud.githubusercontent.com/assets/4368952/21583811/bd1ef6fc-d077-11e6-9bc1-7d6a330bfbb8.png)

But what is expected is this (False image, just illustrative):

![2](https://cloud.githubusercontent.com/assets/4368952/21583812/bd1f72ee-d077-11e6-86f8-af1942f507ff.png)

------
```php
<?php

use Sami\Sami;

//Filter
use Sami\Parser\Filter\TrueFilter;

//Reflection
use Sami\Reflection\MethodReflection;
use Sami\Reflection\PropertyReflection;

$dir = realpath('../test');

if (!$dir) {
    echo 'Invalid path';
    return false;
}

class CustomFilter extends TrueFilter
{
    public function acceptMethod(MethodReflection $method)
    {
        return $method->isPublic() || $method->isProtected();
    }

    public function acceptProperty(PropertyReflection $property)
    {
        return $property->isPublic() || $property->isProtected();
    }
}

$sami = new Sami($dir);

$sami['filter'] = function () {
    return new CustomFilter;
};
return $sami;
```

**Comment by CharlotteDunois** [comment]
I am experiencing this bug as well (and it sucks), any news on this?

**Comment by CharlotteDunois** [comment]
Replace
```
{%- if parameter.default %} = {{ parameter.default }}{% endif %}
```
with
```
{%- if parameter.default != null %} = {{ parameter.default }}{% endif %}
```
in `Sami/Resources/themes/default/macros.twig` and the issue will be gone.

**Comment by brunoaugusto** [comment]
I'm not involved with the development of SAMI but wouldn't that create another issue with optional arguments without default values (i.e. `NULL`)?

By the look of this pseudo-code I would assume a better approach would be:

    {%- if parameter.default != null %} = {{ parameter.default }} {% else %}NULL{% endif %}

Or something similar, since I don't use Twig I'm not aware of the syntax. The idea would be accepting the default value "as is" and force a literal `NULL` for optional arguments without a default value.

**Comment by CharlotteDunois** [comment]
@brunoaugusto A default value of `NULL` is a string with the content `NULL` in SAMI.

**Comment by brunoaugusto** [comment]
In that case, if a literal `NULL` is already covered, then your solution should suffice indeed

**Comment by fabpot** [comment]
I would replace  `if parameter.default != null` by `if parameter.default is not null`. @CharlotteDunois Can you submit a pull request for this bug fix? Thanks.
