### ISSUE TITLE
Parse error on latest phar located at http://get.sensiolabs.org/sami.phar

### ISSUE THREAD

**Issue by cmtatro85** [FriendsOfPHP/Sami#260]
Wasn't sure of where else to put this issue but the latest phar file is causing a parse error.

http://get.sensiolabs.org/sami.phar

`Parse error: syntax error, unexpected '.' in phar:///usr/bin/sami/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1549`

PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37)

**Comment by fabpot** [comment]
Sami 4.0 is only compatible with PHP 7+. If you want PHP 5.5 support, you need to download http://get.sensiolabs.org/sami-v3.3.0.phar

**Comment by althaus** [comment]
Would be nice if this would be stated somewhere out of the `composer.json`. Just pulled from the default location and wondered what went wrong.

http://symfony.com/projects/sami is outdated, too.
