### ISSUE TITLE
Have @param void not generate errors

### ISSUE THREAD

**Issue by philip** [FriendsOfPHP/Sami#262]
Parsing code with "@param void" yields the following error:
```
ERROR: "0" @param tags are expected but only "1" found on ...
```
Seems Sami should ignore "@param void".

Unrelated: consider removing the word "only" in that error.

**Comment by aik099** [comment]
What `@param void` means? Is this valid by PhpDoc?

**Comment by philip** [comment]
1. It means there aren't any parameters, similar to using `@return void` if there isn't a return value. 
2. The phpDocumentor tool does not report errors for this, although doxygen does report them.

I'm not sure how common using this is but google shows a lot of results. However, doesn't seem any doc generator requires it so I'll prompt for their removal. 

That said, setting this to either won't fix or something to discuss later would be understandable by me.

**Comment by aik099** [comment]
Since the `@param void` syntax isn't a standard officially, but people use it for their own reasons I would recommend leaving this as is or maybe reporting better error message back.

@fabpot, ideas?

**Comment by fabpot** [comment]
Never seen that before. The syntax is `@param $foo void`? Not sure I understand. Anyway, that's not supported. Closing this issue. Feel free to open a pull request to add support.
