### ISSUE TITLE
sami fails to parse nullable types with php 7.1.

### ISSUE THREAD

**Issue by temp** [FriendsOfPHP/Sami#264]
Sami Version is 4.0
PHP Version is 7.1.0

Example:
```php
public function getUser(): ?User {}
```

Error:
```
[ErrorException]
  Catchable Fatal Error: Object of class PhpParser\Node\NullableType could not be converted to string in phar:///Users/swentz/bin/sami.phar/Sami/Parser/NodeVisitor.php line 158
```

https://wiki.php.net/rfc/nullable_types

**Comment by derFunk** [comment]
The nullable type is returned from https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/NullableType.php which already supports PHP 7.1.
