### ISSUE TITLE
(Namespaced) functions do not appear in documentation?

### ISSUE THREAD

**Issue by abayob** [FriendsOfPHP/Sami#266]
I have some support functions that live in the global namespace or have a unique namespace.

E.g. 

```
<?php
/**
 * Logging functions
 */

namespace Tools\Logging;

/**
 * Log data to logfile
 * @param  mixed $data The data to be logged
 * @param  string $filename The filename where to logging function was called
 * @return nothing
 */
function write($data, $filename) {
  // Code goes here
}
```

However, these functions do not appear in the generated documentation.
They do get found by the Symfony Finder?

Does Sami only support classes?

**Comment by net-tools** [comment]
Hi,

I have the same issue with my PHP files. I don't know if it's a bug or not.

If the function **do** need to be documented, you could put it in a dummy class : 

```
class LoggingTools
{
     static function write($data, $filename)
     {
          // code here
     }
}
```

and then : `LoggingTools::write('hi !', '/tmp/output.txt');`.

**Comment by abayob** [comment]
Thanks for the tip, I also document the functions with phpDocumentor, so I do have the documentation. 
But Sami is just better, mainly because of the search function and the great overview.

I just hope this is easily fixable 😄

**Comment by fabpot** [comment]
Indeed, Sami does not support functions.
