### ISSUE TITLE
Multiple local versions

### ISSUE THREAD

**Issue by core23** [FriendsOfPHP/Sami#271]
Is there a way to generate API documentation for multiple branches based on local directories?

- /var/doc/master 
- /var/doc/2.x
- /var/doc/3.x

So we can use something like

```
$versions = FileVersionCollection::create('/var/doc/')
    ->add('2.x', '2.0 branch')
    ->add('3.x', '3.0 branch')
    ->add('master', 'master branch')
;

return new Sami($iterator, array(
    'versions' => $versions,
   // ...
));
```

I'm asking because we try to include this in our build server (Bamboo) which loads manual defined branches in a local build directory where we can't access GIT information to use `GitVersionCollection` afterwards.

**Comment by aik099** [comment]
Yes, it's possible. Just specify this in your configuration:

```php
'build_dir' => '/var/doc/%version%',
'cache_dir' => '/var/cache/%version%',
```

You can of course specify any cache dir, but it must include `%version`.

**Comment by core23** [comment]
Maybe you got me wrong.

I have multiple local directories with different sourcecode versions of the same project.

The `build_dir` and `cache_dir` are for generated files based on the sourcecode.

**Comment by aik099** [comment]
I see. I'm afraid there is no way to do this currently.

But you can create custom version collection class by extending from `VersionCollection` class and write version switching logic in there. That would be a great feature if you can submit PR with that class afterwards.

**Comment by aik099** [comment]
By the way `build_dir` setting is where generated docs would be stored. If I understood your scenario correctly you want single documentation with version switcher to be generated even of code for each version is located in it's own folder (probably not under VCS control, but that doesn't matter).

**Comment by core23** [comment]
> By the way build_dir setting is where generated docs would be stored. If I understood your scenario correctly you want single documentation with version switcher to be generated even of code for each version is located in it's own folder (probably not under VCS control, but that doesn't matter).

Correct

**Comment by aik099** [comment]
Good luck with writing `FileVersionCollection` class then. If you need any help feel free to post questions here.

**Comment by fabpot** [comment]
Closing and there is apparently nothing to do in Sami itself.
