### ISSUE TITLE
Add support for $this as class alias

### ISSUE THREAD

**Issue by TheRealDarklord** [FriendsOfPHP/Sami#273]
Hey, would you mind adding $this as an alias for the class name in the resolveAlias function of the class NodeVisitor? It's (imho) a common case to use '@return $this' for fluent interfaces. In fact, PHPStorm uses this as the default return if the method does return $this.

**Comment by aik099** [comment]
I've checked on https://phpdoc.org/docs/latest/guides/types.html and it's officially supported data type. I think we can handle it as `static` data type.

Send a PR please.
