### ISSUE TITLE
Out of date .phar

### ISSUE THREAD

**Issue by schodemeiss** [FriendsOfPHP/Sami#279]
The phar at http://get.sensiolabs.org/sami.phar (which is the suggested way to use this package) is currently on 4.0.1-DEV, which seems a little out of step with the releases. Can we get the phar updated to include the new, awesome, @todo features?

**Comment by fabpot** [comment]
The new feature was just merged. Please, be patient :)

**Comment by schodemeiss** [comment]
Apologies, I didn't mean "immediately" - just in the future, when possible. I'm just aware there was also a 4.0.2 release that the .phar didn't seem to ever get updated with.

**Comment by fabpot** [comment]
4.0.3 is out. The previous phar was 4.0.2, but I forgot to bump the version back then.

**Comment by schodemeiss** [comment]
@fabpot Awesome, thank-you. Apologies again, didn't mean to rush you.
