### ISSUE TITLE
Sami just quits when asked to render

### ISSUE THREAD

**Issue by carbontwelve** [FriendsOfPHP/Sami#280]
When using sami to render API output for https://github.com/carbontwelve/tapestry/tree/development it successfully completes the parse command, but when asked to render or update I get the following:

 ```
F:\Lab\tapestry>sami render sami.php
 Rendering project

Version master

F:\Lab\tapestry>sami update sami.php
 Updating project

F:\Lab\tapestry>

```

The cache directory appears to have lots of json files in it but the docs directory just ends up with css, fonts, ks, PROJECT_VERSION and SAMI_VERSION.

Am I doing something wrong?

**Comment by webcoder31** [comment]
Hi ! 
I meet the same issue. Any idea what's going wrong ?

My files are organised as follow:

- [src]
    - ClassXxx.php
    - ClassYyy.php
- [sami]
    - config.php
    - sami.phar

My config file is:

```
<?php

use Sami\Sami;
use Symfony\Component\Finder\Finder;

$iterator = Finder::create()
    ->files()
    ->name('*.php')
    ->in(__DIR__ . '/../src');

$sami = new Sami($iterator, array(
    'title' => 'EZXMLDSIG Documentation',
    'build_dir' => __DIR__ . '/../docs', 
    'cache_dir' => __DIR__ . '/cache'
));

return $sami;
```

And I run the following command (on Windows 7):

`> php sami/sami.phar update sami/config.php`

Thanks in advance ;)

**Comment by TiS** [comment]
We have encountered similar problem. It turned out, that the culprit was low memory limit setting. On windows PHP somehow did not show any message, just failed silently when encountering it (maybe it wrote to Windows event log, we did not check that).

**Comment by carbontwelve** [comment]
@TiS how much memory does this process require? I have 128M set as the limit on my dev box.

**Comment by TiS** [comment]
It depends on the size of your documentation, I suppose. I manually set memory limit to 1GB in sami config file (via `ini_set('memory_limit', '1G')`).

**Comment by fabpot** [comment]
Closing as there is no "bug" apparently.

**Comment by carbontwelve** [comment]
@fabpot it would be nice if it returned a error or warned about the memory limit possibly being an issue.
