### ISSUE TITLE
Cache makes template development difficult

### ISSUE THREAD

**Issue by shmax** [FriendsOfPHP/Sami#282]
Hi guys, great project.

What is the recommended work flow for developing a new template? Because the source code that is being parsed is not changing everything is pulled from the "cache" folder and I have to delete the cache folder if I want to see my template changes. Is there a command line option to disable the cache, or something? 

Please advise. Thanks!

**Comment by JoeScylla** [comment]
You can use the `--force` parameter with the commands `parse`, `render` or `update`. With `--force` the cache will not get used at all.

	./sami.phar parse --force ./path/to/config.php 
	./sami.phar render --force ./path/to/config.php 
	./sami.phar update --force ./path/to/config.php

**Comment by shmax** [comment]
Ah, wonderful. I've long since moved on, but better late than never. Thanks for the response!
