### ISSUE TITLE
[Feature] Copy Namespace Button

### ISSUE THREAD

**Issue by d3f3kt** [FriendsOfPHP/Sami#283]
Hey folks, 

I really got annoyed the last days by reading through sami documented projects because there is no functionality to copy/paste the namespace of a class. 

I would like to implement a "copy" button next to the namespace breadcrumb bar, which is using a js lib like https://clipboardjs.com/. Is it worth a pull request? Share your opinion.

**Comment by aik099** [comment]
Why you can't use browser copy/paste feature (select text > press ctrl+c) as on other web pages?

**Comment by d3f3kt** [comment]
Thats not possible because the namespace breadcrumb section is not a real text field. The backshlashes are implemented with the css ::before selector. 

So if you select and copy the namespace you will paste it without the backslashes. For example you will get something like this ```Symfony Component HttpFoundation Request```

**Comment by aik099** [comment]
Then maybe you should aggress that instead? Like making namespace a real copyable text.

I guess `::before` selector solution, when developed, wasn't accounting for the fact that text should be copied.

**Comment by d3f3kt** [comment]
I had the same idea, but i thought it would be fancier with a copy button. 

But ok - i will create a PR which makes the namespace breadcrumb copyable.

**Comment by d3f3kt** [comment]
Update: I tried to add li elements with backslashes between the breadcrumbs. 

But you still copy spaces e.g. ```Symfony \ Component \ HttpFoundation \ Request``` 
I will create a pr with the copy to clipboard libary, lets see what @fabpot will say.
