### ISSUE TITLE
@inheritdoc doesn't work

### ISSUE THREAD

**Issue by evgpisarchik** [FriendsOfPHP/Sami#292]
Check the repository https://github.com/evgpisarchik/sami-inheritdoc-issue
(generated docs attached)

### Description of the problem:
Class **A** has method **foo** with description.
Class **B** extends **A** and has its own implementation of **foo** which is annotated with @inheritdoc.

### Actual behavior:
After documentation generation method **foo** of class **B** has no description.

### Expected behavior:
Method **foo** of class **B** should have the same description as method **foo** of class **A**.

**Comment by Merfilde** [comment]
I have the same problem.

**Comment by azurre** [comment]
Use {@inheritdoc} instead

**Comment by evgpisarchik** [comment]
Works for me.
Thanks for the information.
