### ISSUE TITLE
View source link is randomly wrong or not perfect

### ISSUE THREAD

**Issue by mikaelcom** [FriendsOfPHP/Sami#293]
Here is my sami.php configuration file :

```php
use Sami\RemoteRepository\GitHubRemoteRepository;
use Sami\Version\GitVersionCollection;

$versions = GitVersionCollection::create($src = __DIR__ . '/PackageGenerator/src')
    ->add('develop', 'develop branch')
    ->add('master', 'master branch');

return new Sami\Sami($src, [
    'versions' => $versions,
    'title' => 'Package Generator Documentation',
    'build_dir' => __DIR__ . '/www/%version%',
    'cache_dir' => __DIR__ . '/cache/%version%',
    'remote_repository' => new GitHubRemoteRepository('wsdltophp/packagegenerator', dirname($src)),
]);
```

For two classes located in the same directory, the `View source` link is not correct for at least one class such in the [AbstractGeneratorAware](http://doc.wsdltophp.com/develop/WsdlToPhp/PackageGenerator/Generator/AbstractGeneratorAware.html) class.

Do you have any idea why?

In addition the `View source` link in the [Generator](http://doc.wsdltophp.com/develop/WsdlToPhp/PackageGenerator/Generator/Generator.html) class contains two slashes (//) after `src` which is not great.

Thanks 😄

**Comment by aik099** [comment]
Can you please also post here:

* actual link used in docs (copied from `View Source`)
* correct link that should be in docs

**Comment by mikaelcom** [comment]
- AbstractGeneratorAware:
    - current: https://github.com/wsdltophp/packagegenerator/blob/develop/Generator/AbstractGeneratorAware.php
    - expected: https://github.com/wsdltophp/packagegenerator/blob/develop/src/Generator/AbstractGeneratorAware.php

- Generator:
    - current: https://github.com/wsdltophp/packagegenerator/blob/develop/src//Generator/Generator.php
    - expected: https://github.com/wsdltophp/packagegenerator/blob/develop/src/Generator/Generator.php

**Comment by mikaelcom** [comment]
I updated to the latest version and it worked.

By the way, having the [version number](https://github.com/FriendsOfPHP/Sami/blob/master/Sami/Sami.php#L37) as a constant made me sad, it has been [reported before](https://github.com/FriendsOfPHP/Sami/issues/297) and could be set dynamically using the current tag name on phar generation or at least it could be updated when a new release is created.

thx anyway

**Comment by smith86n** [comment]
Yay yoz yo
