### ISSUE TITLE
Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName

### ISSUE THREAD

**Issue by fantiq** [FriendsOfPHP/Sami#294]
find this error and issue #252 
## env
my environment
```
php version : 7.0.8
sami version : 4.0.6
```
## error
when i run this command `sami update config.php` , i got this error:
```
 [ErrorException]
 Notice: Undefined property: PhpParser\Node\Stmt\Class_::$namespacedName in 
 .....\vendor\sami\sami\Sami\Parser\NodeVisitor.php line 115
```

## maybe
i debug the code and find this error probably because the `anonymous class` 

## replicate
when i generate the doc from the source code like this:
```
class Foo
{
    public function bar()
    {
        $class = new class() {};
    }
}
```
i replicate this bug, the sami will analysis the anonymous class as a normal class, but the anonymous class has not name and namespace ？

**Comment by fabpot** [comment]
Can you have a look at how we could fix this?

**Comment by netroby** [comment]
Got the same issue

**Comment by SerafimArts** [comment]
Same

**Comment by SerafimArts** [comment]
UPD: This error will fixes if remove the usage of anonymous classes

**Comment by esilvas** [comment]
I receive the same error.

**Comment by FractalizeR** [comment]
I think this is a problem of nikic/php-parser, not of Sami package. I have the same problem running PHPMetrics on my project (it uses nikic/php-parser to do analysis).

**Comment by paulofreitas** [comment]
I got the same error while trying to generate the Laravel 5.5 code documentation. It breaks while processing this trait which also uses anonymous classes: https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Testing/Concerns/InteractsWithExceptionHandling.php

Nevertheless I was able to parse this file with the same `nikic/php-parser` version used by the Sami itself.

My `composer show`:

```
blackfire/php-sdk                 v1.9.1 Blackfire.io PHP SDK
composer/ca-bundle                1.0.7  Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
michelf/php-markdown              1.7.0  PHP Markdown
nikic/php-parser                  v3.1.0 A PHP parser written in PHP
phpdocumentor/reflection-docblock 2.0.5 
pimple/pimple                     v3.2.2 Pimple, a simple Dependency Injection Container
psr/container                     1.0.0  Common Container Interface (PHP FIG PSR-11)
psr/log                           1.0.2  Common interface for logging libraries
sami/sami                         v4.0.6 Sami, an API documentation generator
symfony/console                   v3.3.8 Symfony Console Component
symfony/debug                     v3.3.8 Symfony Debug Component
symfony/filesystem                v3.3.8 Symfony Filesystem Component
symfony/finder                    v3.3.8 Symfony Finder Component
symfony/polyfill-mbstring         v1.5.0 Symfony polyfill for the Mbstring extension
symfony/process                   v3.3.8 Symfony Process Component
symfony/yaml                      v3.3.8 Symfony Yaml Component
twig/twig                         v2.4.3 Twig, the flexible, fast, and secure template language for PHP
```

**Comment by FractalizeR** [comment]
```NodeVisitor::addClassOrInterface``` needs to be patched for anonymous class support. You can do it like it did it here: https://github.com/phpmetrics/PhpMetrics/pull/299

**Comment by smith86n** [comment]
Database​ components

**Comment by smith86n** [comment]
Try​ APl codes with roi

**Comment by vesper8** [comment]
having this problem too trying to generate the api docs for Laravel 5.5

Am using the dev-master and am using the sami/composer.json from the laravel.com website so I don't understand how come it works for the production site but doesn't work on my dev. Plus didn't you fix this 17 days ago?

**Comment by paulofreitas** [comment]
@vesper8 The `composer.lock` file from https://github.com/laravel/laravel.com/tree/master/build/sami was left outdated. The build script that makes Sami documentation there is using `composer install`. Taylor probably force-fixed this manually. 👍
