### ISSUE TITLE
http://get.sensiolabs.org/sami.phar is out of date

### ISSUE THREAD

**Issue by delamart** [FriendsOfPHP/Sami#297]
Current version is 4.0.6 and get.sensiolabs.org has version 4.0.4

Is the phar being updated manually? would it be possible to have a CI/CD solution update it automatically?

**Comment by johmue** [comment]
Looks like it's an issue with the code in master and 4.0.6.

https://github.com/FriendsOfPHP/Sami/blob/8d2912faff2876c8818a41ece5da3e63dd17b88f/Sami/Sami.php#L30-L45

**Comment by brunoaugusto** [comment]
Any word on this?

I can see on Packagist that current version is 4.0.8 but whenever I download the PHAR from SensioLabs, manually or with cURL (who knows...), and check the version it still shows 4.0.4.

If it's not just "cosmetic", is there an alternative way to download SAMI? Composer and I... don't go along very well ^_^

**Comment by fabpot** [comment]
It's just a problem of the version number, but the code is the last one. I've just released 4.0.9 which shows the right version in the phar.
