### ISSUE TITLE
Class-level @see tag not rendered

### ISSUE THREAD

**Issue by dborsatto** [FriendsOfPHP/Sami#301]
I am experiencing a problem where `@see` annotations on classes are not visible in the final output.
For instance, you can see how this
https://github.com/contentful/contentful-management.php/blob/master/src/Management/Resource/Space.php
is rendered like this
https://contentful.github.io/contentful-management.php/api/master/Contentful/Management/Resource/Space.html

According to [phpDoc's specs](https://docs.phpdoc.org/references/phpdoc/tags/see.html), `@see` can be applied to structural elements, thus including classes. Am I missing something, or is Sami ignoring the annotation? On methods the annotation is rendered correctly (though it'd be nice if it were displayed as an actual link instead of simple text).

**Comment by smith86n** [comment]
It's a code thread it need to be recorded with .Com a internet Link

**Comment by carbontwelve** [comment]
There looks to be a working pull request (#289) that includes this functionality.
