### ISSUE TITLE
ErrorException: count() Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by SerafimArts** [FriendsOfPHP/Sami#302]
- PHP: 7.2.0beta3 (cli, NTS)
- ZE: v3.2.0-dev
- OS: Linux Mint x64
- Sami: v4.0.6

### Error:
```
[ErrorException]                                                             
  Warning: count(): Parameter must be an array or an object that implements 
  Countable in ~/vendor/sami/sami/Sami/Version/SingleVersionCollection.php line 18
```

### I think...

PHP 7.2 can not count non-countable items. `SingleVersionCollection` contain `count($this->versions)` code string, but `$this->versions` contins `null`.

**Comment by SerafimArts** [comment]
UPD:

Source:
```php
class SingleVersionCollection extends VersionCollection
{
    public function add($version, $longname = null)
    {
        if (count($this->versions)) {
            throw new \LogicException('A SingleVersionCollection can only contain one Version');
        }
```

Must be updated to:
```php
class SingleVersionCollection extends VersionCollection
{
    public function add($version, $longname = null)
    {
        if (null !== $this->versions && count($this->versions)) {
            throw new \LogicException('A SingleVersionCollection can only contain one Version');
        }
```

**Comment by fabpot** [comment]
Can you submit a pull request with your changes? Is it the only place where such a change should be made?

**Comment by SerafimArts** [comment]
>  Is it the only place where such a change should be made?

I did not check the other use-cases, but because in the remaining versions are mandatory to indicate there is certainty that yes, the only one place.

> Can you submit a pull request with your changes?

kk

**Comment by fabpot** [comment]
I was more talking about usages of `count()` in other parts of the code.

**Comment by SerafimArts** [comment]
> I was more talking about usages of `count()` in other parts of the code.

¯\\\_(ツ)\_/¯

**Comment by squatto** [comment]
For those that stumble on this while looking for this error, I had to use php 7.1 instead of 7.2 on my project to get around this error. The framework I'm using doesn't fully support 7.2 yet.

**Comment by fabpot** [comment]
@squatto If you are using the latest version of Sami, this should work on 7.1 and 7.2 without problems.

**Comment by squatto** [comment]
I'm using PyroCMS (which is built on Laravel), but the error could apply to any setup. I came across this post from a search of the error and figured that I wouldn't be the only one ;)
