### ISSUE TITLE
Showing only global namespace

### ISSUE THREAD

**Issue by besrabasant** [FriendsOfPHP/Sami#304]
I am using `sami` to generate docs for my **Laravel** project but all the documented classes appear to be under the **Global Namespace**. I want them to be documented under *sub namespaces*.

How do I resolve the issue?

**Comment by smith86n** [comment]
Write a new code rename it, I do it that way.

**Comment by besrabasant** [comment]
The issue was resolved. I had to force rebuild the docs using `--force` argument. Thanks @smith86n .

**Comment by smith86n** [comment]
Global showing , you need a International community namespace of Data codes.
