### ISSUE TITLE
Inconsistent result on Index Page

### ISSUE THREAD

**Issue by brunoaugusto** [FriendsOfPHP/Sami#309]
I didn't find a similar issue but, in any event, it seems there's an inconsistency with the Index Page (not the "homepage")

Thing is that class properties listed there are being named as `$<Classname>` instead of their own names or what I believe to be the most appropriate `Classname::$propertyName`. E.g:

This is a property named `$request` in a class called `Application`:

![screenshot-2017-10-31 next application application next framework](https://user-images.githubusercontent.com/1514089/32230414-462173f2-be3a-11e7-8a96-b9587a25f395.png)

And this is how it appears in the Index:

![screenshot-2017-10-31 index next framework](https://user-images.githubusercontent.com/1514089/32230438-51d61cca-be3a-11e7-997f-b0ec94d2d48d.png)

I would expect it to be at least `$request`, but like I said, IMHO, `Application::$request` would look better.

[OFF]

Any reason for the looks of "Property in class X" to be that much different in Firefox? In Chrome it looks "normal", I mean, without the (excessive) bold

**Comment by CharlotteDunois** [comment]
The issue is in the `property_link` macro in `macros.twig`. It only shows the class by default (for method it shows the method, too). I don't know what's the reason for only showing the class, it doesn't even make sense to me.

**Comment by fabpot** [comment]
@CharlotteDunois Looks like a bug to me. Would you like to submit a pull request for to change this?
