### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by serieznyi** [FriendsOfPHP/Sami#333]
I have some proposition.
How about if I try little clear code

- add more docblock for classes, methods and properties
- fix some autocomplete errors
- change old array notation on neI have some proposition.
How about if I try little clear of code

- add more docblock for classes, methods and properties
- fix some autocomplete errors
- change old array notation on new `[]`
- add type of return statement 
- add argument types in methods
- add type of return statement 
- add argument types in methods
- ... etc

**Comment by fabpot** [comment]
Hi @serieznyi. Thanks for trying to help. However, I would not spend time on anything that does not bring direct value to Sami. Adding docblocks, array notation, ... are not things that looks interesting to me (especially as Sami is not a library but something people use as a tool).

**Comment by serieznyi** [comment]
Ok
