### ISSUE TITLE
Fatal error - @see reference to a missing function

### ISSUE THREAD

**Issue by weitzman** [FriendsOfPHP/Sami#335]
Hi all. My parsing started failing with the most recent release. After quite some debugging, the problem was a @see reference to a function that no longer existed. The printed error is below. I'm not sure if this fatal is expected behavior. If so, feel free to close this.

```
 [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function getAliases() on null 
```

**Comment by fabpot** [comment]
@TiS Can you have a look at this issue? It looks like it was introduced by your PR I merged last week. Thanks.

**Comment by TiS** [comment]
@fabpot I'll check that.

**Comment by krzysiekpiasecki** [comment]
Version "sami/sami": "4.0.14" works, "4.0.15" produces the  same Error.

**Comment by GrahamCampbell** [comment]
Same here.

**Comment by chregu** [comment]
Same issue here. Is there a way to download the phar for 4.0.14 in the meantime? Would save me some work in building and uploading one by myself for our CI runners.

**Comment by TiS** [comment]
@GrahamCampbell @chregu - The initial contributor marked this as "After quite some debugging, the problem was a @see reference to a function that no longer existed.". Please, check, if this is also your case.

I'm looking onto this issue and I'll try to prepare a PR with fix in a day or two.

**Comment by chregu** [comment]
yes, that may well be an issue. But it's in an old version (which we also generate), so not easy to fix without just excluding that.

Thanks for taking care.

**Comment by TiS** [comment]
@fabpot Please review the proposed hotfix.

**Comment by jwage** [comment]
Can we generate a new phar with this fix? I am using Sami now for the Doctrine API docs and I am running in to this error using the 4.0.14-DEV phar. Thanks!

**Comment by fabpot** [comment]
v4.0.16 was released with this bug fix just after merging this PR.

**Comment by fabpot** [comment]
But I forgot to update the version number :)

**Comment by jwage** [comment]
@fabpot thanks! I checked the version number after downloading the phar linked in the readme and didn't see it change so that makes sense.
