### ISSUE TITLE
Link to code on github

### ISSUE THREAD

**Issue by jwage** [FriendsOfPHP/Sami#341]
Would you accept an enhancement to link to the code on github or should I implement this custom for doctrine-project.org? This was requested here https://github.com/doctrine/doctrine-website/issues/89

**Comment by fabpot** [comment]
I would happily accept a pull request doing so in a configurable and optional way.

**Comment by jwage** [comment]
I started to look at implementing this when I realized it was already implemented in #91 and #186.
