### ISSUE TITLE
Please re-enable support for PHP 7.0 again

### ISSUE THREAD

**Issue by cschaba** [FriendsOfPHP/Sami#354]
what is the reason you dropped support for PHP 7.0?

Please, add support for PHP 7.0 again, I have no chance to update my dev systems in the moment.

cs.

**Comment by fabpot** [comment]
Don't upgrade then. Use http://get.sensiolabs.org/sami-v4.0.16.phar

**Comment by brunoaugusto** [comment]
I've been off for some time so, would you mind telling what's the minimum version now? 'Cause in the main README still just PHP 7
