### ISSUE TITLE
There should be an option to use folder structure, or @package for non-namespaced projects

### ISSUE THREAD

**Issue by Finalfantasykid** [FriendsOfPHP/Sami#77]
I have a project which does not use namespaces (please don't lecture me...), but it would be nice if Sami still listed all the classes grouped by folders instead of by namespace if there was a configuration option to do so.  I see that there is an option 'simulate_namespaces' which seems to take classes with underscores and interpret them as the namespace.  It would be nice if another option would take the folder structure instead.

Also, my project uses @package in the documentation before the classes, maybe this could be used as well?

**Comment by IniZio** [comment]
Hope to reactivate this issue as it is pretty common to use folder structure as the namespace? Would be especially convenient for initial documentation.

**Comment by fabpot** [comment]
Closing as I'm not interested to support this feature in Sami.

**Comment by lucideer** [comment]
Just commenting for posterity if anyone else (like me) is searching for this feature in Sami.

I completely understand @fabpot's decision not support this, but I had to undertake a project replacing a really ancient PHP codebase in its entirety, and wanted to use Sami do document the old codebase, so I used the configuration below, which worked perfectly:

https://gist.github.com/lucideer/1330ec5264e7d729dd0e825c51df2e32
