### ISSUE TITLE
Add support for direct urls

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#82]
Sami generates the the most useful API I've ever seen, but one thing I miss is changing URL when I navigate the documentation. I think this can be achieved with `pushstate` and then on `popstate` we'll load page content with ajax.

Also link in tree are H1 and not A, which is bad for SEO purposes. Currently with disabled JavaScript (that's what GoogleBot does I think) I see loading indicator instead of left menu.

**Comment by TomasVotruba** [comment]
Can be closed now, right?

**Comment by aik099** [comment]
It can if Sami version, that don't use frames (e.g. 3.0) was released.

**Comment by fabpot** [comment]
@aik099 Sami 3.0 was released some time ago.
