### ISSUE TITLE
Support for "sitemap.xml"

### ISSUE THREAD

**Issue by aik099** [FriendsOfPHP/Sami#90]
To increase documentation SEO visibility I propose that we generate `sitemap.xml` file containing urls to all documentation page (e.g. http://www.qa-tools.io/sitemap.xml).

Only pages that can be indexed with JavaScript disabled needs to be present in the sitemap.

I also think that there should be a separate sitemap file per version and one to aggregate them all.

**Comment by fabpot** [comment]
Closing this old issue. If someone wants to implement it, he can submit a pull request, but I don't have time doing it myself anyway.
